# Gitleaks configuration for Blaze Intelligence
# Prevents accidental commit of secrets and API keys

title = "Blaze Intelligence Security Scan"

[extend]
# Use default gitleaks rules
useDefault = true

# Custom rules for sports analytics APIs
[[rules]]
id = "sportsradar-api-key"
description = "SportsRadar API Key"
regex = '''(?i)(sportsradar|sportradar).{0,20}['\"][0-9a-z]{32,}['\"]'''
keywords = ["sportsradar", "sportradar"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["openai", "sk-"]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-_]{95,}'''
keywords = ["anthropic", "sk-ant"]

[[rules]]
id = "cloudflare-api-token"
description = "Cloudflare API Token"
regex = '''[a-zA-Z0-9_-]{40}'''
keywords = ["cloudflare", "cf-token"]

[[rules]]
id = "airtable-api-key"
description = "Airtable API Key"
regex = '''key[a-zA-Z0-9]{17}'''
keywords = ["airtable", "key"]

[[rules]]
id = "notion-api-key"
description = "Notion Integration Token"
regex = '''secret_[a-zA-Z0-9]{43}'''
keywords = ["notion", "secret_"]

[[rules]]
id = "hubspot-api-key"
description = "HubSpot API Key"
regex = '''[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'''
keywords = ["hubspot", "pat-"]

# File allowlist - exclude these files from scanning
[allowlist]
description = "Allowlisted files"
files = [
    '''\.env\.example''',
    '''README\.md''',
    '''\.gitleaks\.toml''',
    '''tests/.*\.test\.js''',
    '''src/data/marketing-stats\.json'''
]

# Path allowlist - exclude these paths
paths = [
    '''node_modules/''',
    '''\.git/''',
    '''dist/''',
    '''build/'''
]

# Commit allowlist - exclude these commits
commits = [
    # Add commit hashes to ignore if needed
]

# Entropy detection settings
[entropy]
min = 3.5
max = 8.0
group = 1

# Keywords that trigger additional scanning
[keywords]
aws = ["aws", "amazon"]
gcp = ["gcp", "google cloud"]
azure = ["azure", "microsoft"]
sports = ["sportsradar", "statcast", "nflverse"]
analytics = ["openai", "anthropic", "claude"]