name = "blaze-billing"
main = "functions/worker.js"
compatibility_date = "2025-08-20"
workers_dev = true

[triggers]
crons = ["0 3 * * 1"]

[[r2_buckets]]
binding = "R2"
bucket_name = "blaze-sports-data-lake"

[vars]
NOTION_DATABASE_ID = "2556c055-8681-816c-97ad-d86fa4d0fa7a"
GITHUB_REPO_OWNER = "blaze-intelligence"
GITHUB_REPO_NAME = "sports-data-2025"

[ai]
binding = "AI"

[placement]
mode = "smart"

[env.production]
name = "blaze-sports-data-production"
route = { pattern = "api.blaze-intelligence.com/*", zone_name = "blaze-intelligence.com" }

[env.production.vars]
ENVIRONMENT = "production"

# KV and D1 bindings commented out - need to be created first
# [[kv_namespaces]]
# binding = "CACHE"
# id = "blaze-sports-cache"

# [[d1_databases]]
# binding = "DB"
# database_name = "blaze-sports-metrics"
# database_id = "blaze-sports-metrics-id"