[env.production]
name = "blaze-stripe-api"
main = "api/stripe-subscription.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[env.production.d1_databases]]
binding = "BLAZE_DB"
database_name = "blaze-intelligence-prod"
database_id = "b9df2f50-6287-40ed-9ec3-ad8d11092c7c"

# KV Storage for sessions and caching
[[env.production.kv_namespaces]]
binding = "BLAZE_KV"
id = "1b4e56b25c1442029c5eb3215f9ff636"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "*"

# Secret environment variables (set via CLI)
# wrangler secret put STRIPE_SECRET_KEY --config wrangler-stripe-api.toml --env production
# wrangler secret put STRIPE_WEBHOOK_SECRET --config wrangler-stripe-api.toml --env production
# wrangler secret put JWT_SECRET --config wrangler-stripe-api.toml --env production