name = "blaze-intelligence"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[env.production]
name = "blaze-intelligence-production"

[[env.production.r2_buckets]]
binding = "BLAZE_STORAGE"
bucket_name = "blaze-intelligence-data"

[[r2_buckets]]
binding = "BLAZE_STORAGE"
bucket_name = "blaze-intelligence-data"

[env.production.vars]
API_VERSION = "1.0.0"
CACHE_TTL = "300"
ENVIRONMENT = "production"
